// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  model

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Address ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Address ) UnmarshalJSON([]byte) error { return nil }
func ( Address ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Address ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Address *Address

func ( Event ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Event ) UnmarshalJSON([]byte) error { return nil }
func ( Event ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Event ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Event *Event

func ( Group ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Group ) UnmarshalJSON([]byte) error { return nil }
func ( Group ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Group ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Group *Group

func ( List ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* List ) UnmarshalJSON([]byte) error { return nil }
func ( List ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* List ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_List *List

func ( Lists ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Lists ) UnmarshalJSON([]byte) error { return nil }
func ( Lists ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Lists ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Lists *Lists

func ( OrgMembership ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* OrgMembership ) UnmarshalJSON([]byte) error { return nil }
func ( OrgMembership ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* OrgMembership ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OrgMembership *OrgMembership

func ( Person ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Person ) UnmarshalJSON([]byte) error { return nil }
func ( Person ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Person ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Person *Person

func ( PersonNote ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PersonNote ) UnmarshalJSON([]byte) error { return nil }
func ( PersonNote ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PersonNote ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PersonNote *PersonNote

func ( Role ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Role ) UnmarshalJSON([]byte) error { return nil }
func ( Role ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Role ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Role *Role

func ( Role2 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Role2 ) UnmarshalJSON([]byte) error { return nil }
func ( Role2 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Role2 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Role2 *Role2

func ( Roles ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Roles ) UnmarshalJSON([]byte) error { return nil }
func ( Roles ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Roles ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Roles *Roles

func ( TextMessage ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* TextMessage ) UnmarshalJSON([]byte) error { return nil }
func ( TextMessage ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* TextMessage ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TextMessage *TextMessage

func ( TextRecipient ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* TextRecipient ) UnmarshalJSON([]byte) error { return nil }
func ( TextRecipient ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* TextRecipient ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TextRecipient *TextRecipient

func ( TextResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* TextResponse ) UnmarshalJSON([]byte) error { return nil }
func ( TextResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* TextResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TextResponse *TextResponse

func ( Venue ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Venue ) UnmarshalJSON([]byte) error { return nil }
func ( Venue ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Venue ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Venue *Venue

func ( Venues ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Venues ) UnmarshalJSON([]byte) error { return nil }
func ( Venues ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Venues ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Venues *Venues
