package main

import (
	"fmt"
	"os"
	"path"

	"sunnyvaleserv.org/portal/model"
	"sunnyvaleserv.org/portal/store"
	"sunnyvaleserv.org/portal/util/log"
)

func main() {
	var (
		tx     *store.Tx
		entry  *log.Entry
		folder model.Folder
		err    error
	)
	if err = os.Chdir("/home/snyserv/sunnyvaleserv.org/data"); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: %s\n", err)
		os.Exit(1)
	}
	store.Open("serv.db")
	entry = log.New("", "import-files")
	defer entry.Log()
	tx = store.Begin(entry)
	for _, g := range tx.Authorizer().FetchGroups(tx.Authorizer().AllGroups()) {
		if g.Name == "SERV Leads" {
			folder.Group = g.ID
		}
	}
	folder.Name = "Samariteam Import"
	folder.ID = 1
	tx.CreateFolder(&folder)
	folder.Parent = 1
	for _, file := range files {
		var (
			doc model.Document
			fh  *os.File
		)
		dir, base := path.Split(file)
		if dir != folder.Name {
			folder.Name = dir
			folder.ID++
			folder.Documents = []*model.Document{}
			tx.CreateFolder(&folder)
		}
		doc.ID = model.DocumentID(len(folder.Documents) + 1)
		doc.Name = base
		folder.Documents = append(folder.Documents, &doc)
		if fh, err = os.Open(os.Args[1] + "/" + file); err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: %s\n", err)
			os.Exit(1)
		}
		tx.CreateDocument(&folder, doc.ID, fh)
		fh.Close()
		tx.UpdateFolder(&folder)
	}
	tx.Commit()
}

var files = []string{
	"Administrator Documents/OES Event Volunteer Response Summary.xlsx",
	"Administrator Documents/Volunteer Spreadsheet Fall 2016.xlsx",
	"CERT Class Evaluations/180111 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180118 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180125 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180208 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180215 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180222 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180224 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180403 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180410 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180417 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180424 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180501 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180508 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180515 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180519 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180918 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/180925 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/181002 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/181009 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/181016 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/181023 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/181030 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/181103 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190115 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190122 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190129 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190205 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190212 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190219 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190226 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190302 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190404 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190411 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190418 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190425 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190502 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190509 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190516 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190905 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190912 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190919 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/190926 CERT Class Evaluations summary.pdf",
	"CERT Class Evaluations/191003 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/191010 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/191017 CERT Class Summary Evaluations.pdf",
	"CERT Class Evaluations/191019 CERT Class Evaluations Summary.pdf",
	"CERT Class Evaluations/200116 CERT Class Evaluations.pdf",
	"CERT Class Evaluations/200123 CERT Class Evaluations.pdf",
	"CERT Class Evaluations/200130 CERT Class Evaluations.pdf",
	"CERT Class Evaluations/200206 CERT Class Evaluations.pdf",
	"CERT Class Handouts/CERT Flow of Victims Chart.pdf",
	"CERT Class Handouts/Week 1 Handout - Car Kit.pdf",
	"CERT Class Handouts/Week 1 Handout - CERT 8-week Preparedness Plan-17.pdf",
	"CERT Class Handouts/Week 1 Handout - CERT Backpack Equipment List 140.pdf",
	"CERT Class Handouts/Week 1 Handout - CERT Program Overview 180111.pdf",
	"CERT Class Handouts/Week 1 Handout - CERT Workdesk Kit 140417.pdf",
	"CERT Class Handouts/Week 1 Handout - Disabilites 090824.pdf",
	"CERT Class Handouts/Week 1 Handout - Earthquake Guide for Disabilitie.pdf",
	"CERT Class Handouts/Week 1 Handout - Earthquake Recommended Actions.p",
	"CERT Class Handouts/Week 1 Handout - Gas Safety - PGE 090407.pdf",
	"CERT Class Handouts/Week 1 Handout - Go Bag Checklist 100421.pdf",
	"CERT Class Handouts/Week 1 Handout - Water Treatment 090407.pdf",
	"CERT Class Handouts/Week 2 Handout - CERT All-Risk Triage Tag 130518.",
	"CERT Class Handouts/Week 2 Handout - CERT Triage Flow Chart 170928.pdf",
	"CERT Class Handouts/Week 2 Handout - CERT Triage Victim Form.pdf",
	"CERT Class Handouts/Week 2 Handout - Safe Search Step-by-Step.pdf",
	"CERT Class Handouts/Week 2 Handout - Search Checklist 4.pdf",
	"CERT Class Handouts/Week 2 Handout - Search Procedures 3.pdf",
	"CERT Class Handouts/Week 2 Handout - Tips for First Responders - 3rd.pdf",
	"CERT Class Handouts/Week 3 Handout - Back Care 180111.pdf",
	"CERT Class Handouts/Week 3 Handout - Heat Related Emergencies 131107.",
	"CERT Class Handouts/Week 3 Handout - Immobilization Skills 131107.pdf",
	"CERT Class Handouts/Week 3 Handout - Rag Bag First Aid Supplies 13110.pdf",
	"CERT Class Handouts/Week 3 Handout - Triage Starter Kit 131107.pdf",
	"CERT Class Handouts/Week 4 Handout CERT Hazardous Materials Placards.pdf",
	"CERT Class Handouts/Week 4 Handout CERT Light Search and Rescue Check.pdf",
	"CERT Class Handouts/Week 4 Handout CERT Neighborhood Damage Assessmen.pdf",
	"CERT Class Handouts/Week 4 Handout CERT Quick Hazard Survey 170928.pdf",
	"CERT Class Handouts/Week 5 Handout CERT Damage Assessment Message For.pdf",
	"CERT Class Handouts/Week 5 Handout CERT FRS Radio Plan Form.pdf",
	"CERT Class Handouts/Week 5 Handout CERT Logistics Equipment Log.pdf",
	"CERT Class Handouts/Week 5 Handout CERT Transfer of Command 201Form 1.pdf",
	"CERT Class Handouts/Week 7 Handout - Shelter in Place Procedures.pdf",
	"CERT Class Handouts/Week 7 Handout - Terror 090409.pdf",
	"CERT Class Handouts/Week 7 Handout - Terror Handout - Israeli Police.",
	"CERT Class Handouts/Week 7 Handout - Terrorism - Active Shooter.pdf",
	"CERT Class Handouts/Week 7 Handout - Terrorism Response - ARC 090409.",
	"CERT Class Handouts/Week 7 Handout - Terrorist Bombing - Response.pdf",
	"CERT Class Handouts/Week 7 Handout - Terrorist Bombing Preparations 0.pdf",
	"CERT Class PDF Presentations/1.0 Class overview 180912.pdf",
	"CERT Class PDF Presentations/1.1 CERT Training Introduction 200116.pdf",
	"CERT Class PDF Presentations/1.2 CERT Disaster Prep - 180912.pdf",
	"CERT Class PDF Presentations/1.3 CERT Gas & Electric Safety - 190113.pdf",
	"CERT Class PDF Presentations/1.4 CERT Emergency Disaster Supplies - 190901.pdf",
	"CERT Class PDF Presentations/2.1 CERT Quick Introduction to ICS - 160908.pdf",
	"CERT Class PDF Presentations/2.2 CERT Disaster Medical Operations 1 190319.pdf",
	"CERT Class PDF Presentations/2.3 CERT START Triage 190315.pdf",
	"CERT Class PDF Presentations/3.1 CERT Disaster Medical Operations 2 190315.pdf",
	"CERT Class PDF Presentations/4.1 CERT Quick Hazards Survey -  170914.pdf",
	"CERT Class PDF Presentations/4.2 CERT Damage Assessment - 170914.pdf",
	"CERT Class PDF Presentations/4.3 CERT Light Search Rescue 181009.pdf",
	"CERT Class PDF Presentations/5.1 CERT Incident Command System 190212.pdf",
	"CERT Class PDF Presentations/6.1 CERT Fire-Suppression 160908.pdf",
	"CERT Class PDF Presentations/6.2 CERT Hazmat 160908.pdf",
	"CERT Class PDF Presentations/6.3 CERT Extinguishers 160908.pdf",
	"CERT Class PDF Presentations/7.1 CERT Terrorism 190228.pdf",
	"CERT Class PDF Presentations/7.2 CERT Communications with City 190225.pdf",
	"CERT Class PDF Presentations/7.3 CERT Communications using Radios 190225.pdf",
	"CERT Class PDF Presentations/7.4 CERT Critical Incident Stress 3X 190904",
	"CERT Class PDF Presentations/7.4 CERT Critical Incident Stress FS 190904",
	"CERT Class PDF Presentations/Flow of Victims Chart.pdf",
	"CERT Class PDF Presentations/ICSLand-BoardgameIntroDemo.pdf",
	"CERT Deployment Docs/CERT DEPLOYMENT PROTOCOL-WL.docx",
	"CERT Forms/190214 LSAR handout.pdf",
	"CERT Forms/Week 2 CERT Form - Victim Treatment Area Record 1.pdf",
	"CERT Forms/Week 2 Form - Head 2 Toe 131016 .pdf",
	"CERT Forms/Week 4 Form - EXAMPLE-Neighborhood Survey Form.pdf",
	"CERT Forms/Week 4 Form - Neighborhood Assessment-General Sur.pdf",
	"CERT Forms/Week 4 Form - Neighborhood Survey Form-General.pdf",
	"CERT Forms/Week 4 Form - Quick Hazard Survey 3 110929.pdf",
	"CERT Forms/Week 4 Form - Victim Treatment Area Record 140107.pdf",
	"CERT Forms/Week 5 CERT Form - All Forms 140107.pdf",
	"CERT Forms/Week 5 CERT Form - Assignment Tracking Log 140108.pdf",
	"CERT Forms/Week 5 CERT Form - Briefing Assignment 140107.pdf",
	"CERT Forms/Week 5 CERT Form - Communications Log 140107.pdf",
	"CERT Forms/Week 5 CERT Form - Damage Assessment 140108.pdf",
	"CERT Forms/Week 5 CERT Form - Equipment Inventory 140108.pdf",
	"CERT Forms/Week 5 CERT Form - ICS-214 140108.pdf",
	"CERT Forms/Week 5 CERT Form - Personnel Resources 140107.pdf",
	"CERT Forms/Week 5 Form - CERT Incident Command Action Items.pdf",
	"CERT Forms/Week 5 Form - CISMcommunications.pdf",
	"CERT Forms/Week 5 Form - General Message 2011.pdf",
	"CERT Forms/Week 5 Form - ICS 214 Blank 110929.pdf",
	"CERT Forms/Week 5 Form - ICS Forms 201 - Incident Briefing 1.pdf",
	"CERT Forms/Week 5 Form - Logistics Check-in Check-out Form 1.pdf",
	"CERT Forms/Week 5 Form - Radio Plan Example 170520 .pdf",
	"CERT Forms/Week 5 Form - Sunnyvale CERT Damage Assessment.pdf",
	"CERT Forms/Week 5 Form - Transfer of Command Form 120921.pdf",
	"CERT Instructor Presentations - PowerPoints/1.0 Class overview 180912.pptx",
	"CERT Instructor Presentations - PowerPoints/1.1 CERT Training Introduction 200116.pptx",
	"CERT Instructor Presentations - PowerPoints/1.2 CERT Disaster Prep - 180912.pptx",
	"CERT Instructor Presentations - PowerPoints/1.3 CERT Gas & Electric Safety - 190113.pptx",
	"CERT Instructor Presentations - PowerPoints/1.4 CERT Emergency Disaster Supplies - 190901pptx",
	"CERT Instructor Presentations - PowerPoints/2.1 CERT Quick Introduction to ICS - 160908.pptx",
	"CERT Instructor Presentations - PowerPoints/2.2 CERT Disaster Medical Operations 1 190319.pptx",
	"CERT Instructor Presentations - PowerPoints/2.3 CERT START Triage 190315.pptx",
	"CERT Instructor Presentations - PowerPoints/3.1 CERT Disaster Medical Operations 2 190315.pptx",
	"CERT Instructor Presentations - PowerPoints/4.1 CERT Quick Hazards Survey -  170914.pptx",
	"CERT Instructor Presentations - PowerPoints/4.2 CERT Damage Assessment - 170914.pptx",
	"CERT Instructor Presentations - PowerPoints/4.3 CERT Light Search Rescue 181009.pptx",
	"CERT Instructor Presentations - PowerPoints/5.1 CERT Incident Command System 190212.pptx",
	"CERT Instructor Presentations - PowerPoints/6.1 CERT Fire-Suppression 160908.pptx",
	"CERT Instructor Presentations - PowerPoints/6.2 CERT Hazmat 160908.pptx",
	"CERT Instructor Presentations - PowerPoints/6.3 CERT Extinguishers 160908.pptx",
	"CERT Instructor Presentations - PowerPoints/7.1 CERT Terrorism 190228.pptx",
	"CERT Instructor Presentations - PowerPoints/7.2 CERT Emergency Communications 190906.pptx",
	"CERT Instructor Presentations - PowerPoints/7.3 CERT Communications using Radios 190905.pptx",
	"CERT Instructor Presentations - PowerPoints/7.4 CERT Critical Incident Stress - 190904.pptx",
	"Cert Related Events , Activities/Link to Cupertino CERT event 160704.pdf",
	"CERT Resource Materials/190901 Arley's Barrel Process.pdf",
	"CERT Resource Materials/8 Week Preparedness Plan.pdf",
	"CERT Resource Materials/Andrew's Bug-Out Bag List.docx",
	"CERT Resource Materials/ARC Checklist.pdf",
	"CERT Resource Materials/ARC Chlorox Brochure.pdf",
	"CERT Resource Materials/ARC Supply Kit.pdf",
	"CERT Resource Materials/Backpack_Kit_Sheet.pdf",
	"CERT Resource Materials/CERT - PEP - Public Safety Power Shutoff Plan -Pa.pdf",
	"CERT Resource Materials/CERT Bag Inventory List.pdf",
	"CERT Resource Materials/CERT Emergency Preparedness Workbook v2.1 110919.",
	"CERT Resource Materials/CERT FOG Manual.pdf",
	"CERT Resource Materials/CERT Head-to-Toe Checklist 160908.pdf",
	"CERT Resource Materials/CERT Map - Associations 151231.pdf",
	"CERT Resource Materials/CERT Severe Weather Manual.pdf",
	"CERT Resource Materials/CERT Web Resources 151114.pdf",
	"CERT Resource Materials/CERT_Participant_Manual_2011_01.pdf",
	"CERT Resource Materials/Emergency Response for People with Disabilities -.pptx",
	"CERT Resource Materials/Emergency_Supplies_for_Animals.pdf",
	"CERT Resource Materials/FEMA - Are You Ready - Part 1.pdf",
	"CERT Resource Materials/FEMA - Are You Ready - Part 2.pdf",
	"CERT Resource Materials/FEMA Emergency Financial First Aid Kit 190428 - S.pdf",
	"CERT Resource Materials/FEMA Emergency Financial First Aid Kit 190428.pdf",
	"CERT Resource Materials/FEMA Emergency Supply List 160108.pdf",
	"CERT Resource Materials/Flood_Safety_Toolkit_2015.pdf",
	"CERT Resource Materials/How to Choose a Reliable Emergency Radio.pdf",
	"CERT Resource Materials/Hurricane_Preparedness_Week_Toolkit_2015.pdf",
	"CERT Resource Materials/Living on Shaky Ground 190428.pdf",
	"CERT Resource Materials/Map - SNAP Districts.pdf",
	"CERT Resource Materials/Protecting Your Family_EN_SP.pdf",
	"CERT Resource Materials/SAMHSA Managing Stress 140610.pdf",
	"CERT Resource Materials/SAMHSA Post Deployment Psychological Guide NMH05-.pdf",
	"CERT Resource Materials/SAMHSA Psychological First Aid for First Responde.pdf",
	"CERT Resource Materials/Santa Clara County Flood Map 150922.pdf",
	"CERT Resource Materials/SCVWD Flood Safe Guide.pdf",
	"CERT Resource Materials/SJ Water Company Potable Water TableTop Exercise.pdf",
	"CERT Resource Materials/Staying Safe Where The Earth Shakes - Statewide E.pdf",
	"CERT Resource Materials/Sunnyvale Emergency Plan.pdf",
	"CERT Resource Materials/Sunnyvale Guide to Emergency and Disaster Prepare.pdf",
	"CERT Resource Materials/Sunnyvale_Personal_Prepardenss_Workbook_SV OES-1.",
	"CERT Resource Materials/The Complete Guide to What To Do Before, During,.pdf",
	"CERT Resource Materials/Timeline-Based Disaster Planning.pdf",
	"CERT Resource Materials/Training Opportunities for Disaster First Aid v2.pdf",
	"CERT Resource Materials/USGS Living on Shaky Ground Magazine FINAL 140901.pdf",
	"CERT Resource Materials/USGS Protecting Your Family From Earthquakes - Se.pdf",
	"CERT Resource Materials/USGS Putting Down Roots in Earthquake Country  -.pdf",
	"CERT Resource Materials/USGS Putting Down Roots in Earthquake Country - S.pdf",
	"CERT Resource Materials/Web Resources 151112.docx",
	"FEMA CERT Training Materials/FEMA CERT Basic Training Instructor Guide Hazard.pdf",
	"FEMA CERT Training Materials/FEMA CERT Train-the-Trainer Full Instructor Guide.pdf",
	"FEMA CERT Training Materials/FEMA CERT Unit 1 Disaster Preparedness.pptx",
	"FEMA CERT Training Materials/FEMA CERT Unit 2 Fire Safety and Utility Controls.pptx",
	"FEMA CERT Training Materials/FEMA CERT Unit 3 Disaster Medical Part 1.pptx",
	"FEMA CERT Training Materials/FEMA CERT Unit 4 Disaster Medical Part 2.pptx",
	"FEMA CERT Training Materials/FEMA CERT Unit 5 Light Search and Rescue.pptx",
	"FEMA CERT Training Materials/FEMA CERT Unit 6 CERT Organization.pptx",
	"FEMA CERT Training Materials/FEMA CERT Unit 7 Disaster Psychology.pptx",
	"FEMA CERT Training Materials/FEMA CERT Unit 8 Terrorism and CERT.pptx",
	"LISTOS/ACTIVITY - BIG Plan De Reunificacion Comunicacion.docx",
	"LISTOS/ACTIVITY - Botiquín artículos.docx",
	"LISTOS/ACTIVITY - Botiquín.docx",
	"LISTOS/ACTIVITY - Gas Valve exercise.docx",
	"LISTOS/ACTIVITY - Gas valve practice.docx",
	"LISTOS/ACTIVITY Boletos de rifa.docx",
	"LISTOS/ACTIVITY fire escape plan answers.docx",
	"LISTOS/ACTIVITY fire escape plan.docx",
	"LISTOS/ACTIVITY Loteria Baraja.docx",
	"LISTOS/ACTIVITY Loteria Tablas.docx",
	"LISTOS/ACTIVITY Rompehielos - Ice Breaker.docx",
	"LISTOS/Certificate Template ENGLISH.pptx",
	"LISTOS/Certificate Template ESPANOL.pptx",
	"LISTOS/ENGLISH Manual Instructor.pdf",
	"LISTOS/ENGLISH Manual Participant.pdf",
	"LISTOS/ESPANOL Manual del Instructor.pdf",
	"LISTOS/ESPANOL Manual del Participante.pdf",
	"LISTOS/HANDOUT -Plan de comunicacion y reunificacion.docx",
	"LISTOS/Lista de Asistentes Sign In Sheet.docx",
	"LISTOS/Lista de Instructores.docx",
	"LISTOS/Lista del comite.docx",
	"LISTOS/LISTOS arrows.docx",
	"LISTOS/LISTOS Bilingual - PhotoRelease.docx",
	"LISTOS/LISTOS Instructor Agreement 2019.docx",
	"LISTOS/LISTOS Logo.jpg",
	"LISTOS/NFUIS - Sign In Sheet Spa.pdf",
	"LISTOS/NFUIS Bilingual  Student Registration.pdf",
	"LISTOS/OUTREACH - Checkoff List.docx",
	"LISTOS/OUTREACH - Lista de interes Interest sign up shee.docx",
	"LISTOS/OUTREACH FLYER - full double sided.pdf",
	"LISTOS/OUTREACH FLYER - tri fold.pdf",
	"LISTOS/OUTREACH FLYER - wallet size.pdf",
	"LISTOS/PROP- Carpeta de Emergencia - Emergency Binder.do",
	"PEP Handouts/Evacuation form.pdf",
	"PEP Handouts/PEP handouts.pdf",
	"PEP Handouts/PEPChklist.docx111707112017.pdf",
	"PEP Handouts/web resources.docx371307112017.pdf",
	"PEP Slides/PEP Slides - Standard - 17 Oct 2019.ppt",
	"PEP Slides/PEP Speaker notes.pdf",
	"PEP/contactevac.docx",
	"PEP/EVACUATION Grab and Go Form.pdf",
	"PEP/PEP Speaker notes.docx",
	"PEP/PEP_Evals.docx",
	"PEP/PEP_Handouts_Oct24 (1).pdf",
	"PEP/PEPChklist.docx",
	"PEP/web resources.docx",
	"SARES Forms/ICS_214-SCCo-ARES-RACES_Unit_Log.pdf",
	"SARES Forms/ICS_309-SCCo-ARES-RACES_Comm_Log.pdf",
	"SARES Forms/ICS-213-SCC-Message-Form-06_28_07.pdf",
	"SARES Forms/SCCo-ARES-RACES_MM_Summary_v100906.pdf",
	"SARES Forms/SNY_CERT_Damage Assessment Rev 1  Nov2016.pdf",
	"SARES/2019 SARES Calendar.pdf",
	"SARES/drill082817.pdf",
	"SARES/SARES Roster Rev 20170701.xlsx",
	"SARES/SARES Training Meeting 17Jan2019_Final.pdf",
	"SARES/SARES Training Meeting 18May2017.pdf",
	"SARES/SARES-brochure2013.pdf",
	"SARES/SARES-FreqList-7-3f-3.pdf",
	"SARES/SARES-netscript.pdf",
	"SARES/SARES-quadrant_police-RD_map.pdf",
	"SERV Leadership Team Meetings/2016 Nov 08 - SERV LT Meeting Agenda and Minutes.",
	"SERV Leadership Team Meetings/2016 Oct 25 - SERV LT Meeting Agenda_Minutes.docx",
	"SERV Leadership Team Meetings/2016 Sep 20 - SERV LT Meeting Agenda_Minutes.docx",
	"SERV Leadership Team Meetings/2017 Jul 25 SERV LT Meeting Agenda_Minutes.docx",
	"SERV Maps/MAP Sunnyvale DPS SERV - 190207.pdf",
	"SFO Exercise/2016AirCrashExerciseFlyer_FINAL (1).docx",
	"SFO Exercise/Volunteer Agreement and Waiver (CCSF) 08-26-16.doc",
	"SNAP - Data & Metrics/MYN COMPLETED - METRICS for 2016.xlsx",
	"SNAP - Data & Metrics/MYN COMPLETED - METRICS for 2017.xlsx",
	"SNAP - Data & Metrics/MYN COMPLETED - METRICS for 2018.xlsx",
	"SNAP - Data & Metrics/MYN COMPLETED - METRICS for 2019.xlsx",
	"SNAP - Data & Metrics/MYN Completed - Neighborhood Summary Information.xlsx",
	"SNAP - MHP MYN/Block Captains followup steps after MYN event.docx",
	"SNAP - MHP MYN/CCV MYN Agenda combined topics & time.docx",
	"SNAP - MHP MYN/CDA MYN Agenda for participants.docx",
	"SNAP - MHP MYN/Docs n supplies for setup MYN multi.docx",
	"SNAP - MHP MYN/Email or talking points for MYN outreach CDA.docx",
	"SNAP - MHP MYN/MYN flyer_2017 CCV 3_19_­17.doc",
	"SNAP - MHP MYN/MYN flyer_CDA_2017.doc",
	"SNAP - MHP MYN/SNAP_Intro to MYN Cape Cod [Autosaved].pptx",
	"SNAP - MHP MYN/SNAP_Intro to MYN Casa de Amigos.pptx",
	"SNAP - MYN/District Map Sunnyvale DPS SERV 2019 02.07.pdf",
	"SNAP - MYN/MYN Discussion - Fire Extinguisher Safety.pdf",
	"SNAP - MYN/MYN Discussion - Natural Gas Shutoff.pdf",
	"SNAP - MYN/MYN Discussion - Search and Rescue.pdf",
	"SNAP - MYN/MYN Discussion - Water and Electricity Shutoff.pdf",
	"SNAP - MYN/MYN DVD Discussion Guide.pdf",
	"SNAP - MYN/MYN EVENT DAY - Presenter Guidelines 18 July 2019.pdf",
	"SNAP - MYN/MYN Event Sign-In Form 10 Jul 2016.docx",
	"SNAP - MYN/MYN Household Resources for Disaster Response v20.pdf",
	"SNAP - MYN/MYN Invitation Outreach Log v.2019 10.08.xlsx",
	"SNAP - MYN/MYN Invitiation.doc",
	"SNAP - MYN/MYN Liaison Guidelines 18 July 2019.pdf",
	"SNAP - MYN/MYN Next Topics 2019.03.28.pdf",
	"SNAP - MYN/MYN Outreach Talking Points  v.2019 10.25.docx",
	"SNAP - MYN/MYN Process Flow 12 Jun 2016.pdf",
	"SNAP - MYN/MYN Reminder.doc",
	"SNAP - MYN/MYN-Overview_Spanish.pdf",
	"SNAP - MYN/MYN-Overview.pdf",
	"SNAP - MYN/Rural Neighborhoods Considerations.pdf",
	"SNAP - MYN/TEMPLATE MYN Liaison Report 25 Sep 2016.docx",
	"SNAP - MYN/Training Opportunities for Disaster First Aid 180.pdf",
	"SNAP - MYN/Vertical Neighborhoods Considerations.pdf",
	"SNAP - People Resources/SNAP PROGRAM - Team Email List 2020 01.12.docx",
	"SNAP Program - Committee/Introducing SNAP handout 180903.pdf",
	"SNAP Program - Committee/SNAP Org Chart 12 Jun 2016.pdf",
	"SNAP-Meeting Minutes/2017 Nov 8 SNAP meeting Minutes.docx",
	"SNAP-Meeting Minutes/2018 01.10 SNAP meeting Agenda.docx",
	"SNAP-Meeting Minutes/2018 03.14 SNAP Meeting Minutes.docx",
	"SNAP-Meeting Minutes/2018 05.09 SNAP meeting Agenda.docx",
	"SNAP-Meeting Minutes/2018 06.13 SNAP meeting Minutes.docx",
	"SNAP-Meeting Minutes/2018 07.11 SNAP meeting minutes.docx",
	"SNAP-Meeting Minutes/2018 08.08 SNAP Mtg Minutes.docx",
	"SNAP-Meeting Minutes/2018 09.12 SNAP meeting Minutes.docx",
	"SNAP-Meeting Minutes/2018 11.14 SNAP meeting Minutes .docx",
	"SNAP-Meeting Minutes/2018 12.12 SNAP Meeting Minutes.docx",
	"SNAP-Meeting Minutes/2019 01.09 SNAP Meeting Minutes Final.docx",
	"SNAP-Meeting Minutes/2019 02.13 SNAP Meeting Minutes.docx",
	"SNAP-Meeting Minutes/2019 03.13 SNAP Meeting Minutes.docx",
	"SNAP-Meeting Minutes/2019 04.10 SNAP Meeting Minutes.docx",
	"SNAP-Meeting Minutes/2019 05.08 SNAP Meeting Minutes.docx",
	"SNAP-Meeting Minutes/2019 06.26 SNAP Meeting Minutes.docx",
	"SNAP-Meeting Minutes/2019 08.14 SNAP Meeting Minutes.docx",
	"SNAP-Meeting Minutes/2019 09.11 SNAP Meeting Minutes.docx",
	"SNAP-Meeting Minutes/2019 10.09 SNAP Meeting Minutes.docx",
	"SNAP-Meeting Minutes/2019 11.20 SNAP Meeting Minutes.pdf",
	"SNAP-Meeting Minutes/2020 01.08 SNAP Meeting Minutes.pdf",
	"SNAP-Meeting Minutes/Aug 9 2017 SNAP Mtg Minutes.docx",
	"SNAP-Meeting Minutes/Dec 7 2016 Meeting Minutes.docx",
	"SNAP-Meeting Minutes/Jan 11 2017 Meeting Minutes.docx",
	"SNAP-Meeting Minutes/July 11 2016 Meeting Minutes.docx",
	"SNAP-Meeting Minutes/July 25 2016 Meeting Minutes.docx",
	"SNAP-Meeting Minutes/June 15 2016 Meeting Minutes.docx",
	"SNAP-Meeting Minutes/June 29 2016 Meeting Minutes.docx",
	"SNAP-Meeting Minutes/May 26 2016 Meeting Minutes.pdf",
	"SNAP-Meeting Minutes/Nov 16 2016 Meeting Minutes.docx",
	"SNAP-Meeting Minutes/Oct 18 2016 Meeting Minutes.docx",
	"SNAP-Meeting Minutes/Sept 13 2017 SNAP Mtg Minutes.docx",
	"SNAP-Meeting Minutes/Sept 26 2016 Meeting Minutes.docx",
	"SNAP-Meeting Minutes/SNAP MEETING MINUTES 4.11.18.docx",
	"SNAP-Meeting Minutes/SNAP Mtg Minutes 2.13.18.docx",
}
